
export const commands = {
    assembly: "nasm -f elf64 -o a.o main.asm && ld -o a.out a.o && ./a.out",
    ats:"make",
    bash:"bash main.sh",
    c:"clang main.c && ./a.out",
    clisp:"sbcl --noinform --non-interactive --load main.lsp",
    clojure:"java -cp /usr/share/java/clojure.jar clojure.main main.clj",
    cobol:"cobc -x -o a.out main.cob && ./a.out",
    coffescript:"coffee main.coffee",
    cpp:"clang++ main.cpp && ./a.out",
    crystal:"crystal run main.cr",
    csharp:"mcs -out:a.exe main.cs && mono a.exe",
    d:"dmd -ofa.out main.d && ./a.out",
    dart:"dart main.dart",
    elixir:"elixir main.ex",
    elm:"elm make --output a.js Main.elm && elm-runner a.js",
    erlang:"escript main.erl",
    fsharp:"fsharpc --out:a.exe main.fs > /dev/null && mono a.exe",
    go:"go run main.go",
    groovy:"groovy main.groovy",
    guile:"guile --no-debug --fresh-auto-compile --no-auto-compile -s main.scm",
    hare:"hare run main.ha",
    haskell:"runghc main.hs",
    idris:"idris2 -o a.out --output-dir . main.idr && ./a.out",
    html:"firefox main.html",
    java:"javac Main.java && java Main",
    javascript:"node main.js",
    julia:"julia main.jl",
    kotlin:"kotlinc main.kt && kotlin MainKt",
    lua:"lua main.lua",
    mercury:"mmc -o a.out main.m && ./a.out",
    nim:"nim --verbosity:0 compile --run main.nim",
    nix:"nix-instantiate --eval main.nix",
    ocaml:"ocamlc -o a.out main.ml && ./a.out",
    pascal:"fpc main.pp -oa.out && ./a.out",
    perl:"perl main.pl",
    php:"php main.php",
    python:"python main.py",
    raku:"raku main.raku",
    ruby:"ruby main.rb",
    rust:"rustc -o a.out main.rs && ./a.out",
    sac:"sac2c -t seq -o a.out main.sac && ./a.out",
    scala:"scalac main.scala && scala Main",
    swift:"swift main.swift",
    typescript:"tsc main.ts && node main.js",
    zig:"zig run main.zig",

}